server:
  port: 8080

spring:
  application:
    name: document-api
  docker:
    compose:
      file: ../docker-compose.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/async_docx
    username: async_docx
    password: async_docx
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    document-generation-topic: document-generation-requests
  documents:
    storage-path: ../generated-documents

management:
  endpoints:
    web:
      exposure:
        include: health,info
